version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb+srv://mongodb:mongodb@cluster0.g8qhp.mongodb.net/demo
      - JWT_SECRET=your_secret_key
      - PORT=5000
  db:
    image: mongo:latest
    ports:
      - "27017:27017"

